apiVersion: v1
kind: Secret
metadata:
  name: local-secret
  namespace: demo
data:
  RESTIC_PASSWORD: bm90QHNlY3JldA==
type: Opaque
---
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: local-repo
  namespace: demo
spec:
  backend:
    local:
      mountPath: /safe/data
      hostPath:
        path: /data/stash-test/restic-repo
    storageSecretName: local-secret
