apiVersion: v1
kind: Pod
metadata:
  name: rest-server
  namespace: demo
  labels:
    app: rest-server
spec:
  containers:
  - name: rest-server
    image: restic/rest-server
    ports:
    - name: http-1
      containerPort: 8000
# kubectl logs -f -n demo rest-server
# kubectl exec -it -n demo rest-server create_user myuser
# kubectl create secret generic rest-secret -n demo --from-file=./RESTIC_PASSWORD --from-file=./REST_SERVER_USERNAME --from-file=./REST_SERVER_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: rest-server
  namespace: demo
  labels:
    app: rest-server
spec:
  ports:
  - port: 8000
    name: http-1
    protocol: TCP
    targetPort: 8000
  type: NodePort
  selector:
    app: rest-server
---
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: hello-repo
  namespace: demo
spec:
  backend:
    rest:
      url: http://172.17.0.4:8000/hello-prefix
    storageSecretName: rest-secret