kind: Pod
apiVersion: v1
metadata:
  name: test-check-dest
  namespace: demo
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh","-c"]
    args:
    - 'set -x; ls /etc/target'
    volumeMounts:
    - mountPath: /etc/target
      name: test-pvc-dest
  restartPolicy: Never
  volumes:
  - name: test-pvc-dest
    persistentVolumeClaim:
     claimName: test-pvc-dest