# volumeBackup function backup a kubernetes volume
apiVersion: stash.appscode.com/v1beta1
kind: Function
metadata:
  name: volumeBackup
spec:
  container:
    image:  appscodeci/volume-tool:v1
    name:  volume-tool
    args:
    - backup
    - --target-directories=${targetDirectories}
    - --provider=${provider}
    - --hostname=${hostname}
    - --path=${repoDir}
    - --output-dir=${outputDir}
    - --retention-policy.policy=${policy}
    - --retention-policy.value=${retentionValue}
    - --metrics.enabled=${enableMetric}
    - --metrics.pushgateway-url=${pushgatewayURL}
    - --metrics.labels="workload-kind=${workloadKind},workload-name=${workloadName}"
    volumeMounts:
    - name: ${tempVolumeName}
      mountPath: /tmp/restic
    - name: ${storageSecretName}
      mountPath: /etc/secrets/storage-secret
