---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: stash
  name: repositories.stash.appscode.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.integrity
    name: Integrity
    type: boolean
  - JSONPath: .status.size
    name: Size
    type: string
  - JSONPath: .status.snapshotCount
    name: Snapshot-Count
    type: integer
  - JSONPath: .status.lastBackupTime
    format: date-time
    name: Last-Successful-Backup
    type: date
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: stash.appscode.com
  names:
    categories:
    - storage
    - appscode
    - stash
    kind: Repository
    plural: repositories
    shortNames:
    - repo
    singular: repository
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  - name: v1beta1
    served: true
    storage: false
